name: .NET Build and Publish Nuget

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'v3.1'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish Bullhorn 
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:   
        PROJECT_FILE_PATH: src/Bullhorn/Bullhorn.csproj  
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    
